apiVersion: apps/v1 
kind: Deployment
metadata:
  name: lqpdevtest-svc-deployment
  namespace: default
spec:
  selector:
    matchLabels:
      app: lqpdevtest-eks
  replicas: 1
  template:
    metadata:
      labels:
        app: lqpdevtest-eks
    spec:
      containers:
      - name: lqpdevtest
        image: 614191790445.dkr.ecr.us-east-2.amazonaws.com/lqpdevtest:latest
        env:
        - name: KAFKA_REST_PROXY_URL
          value: "http://172.31.37.218:8082"
        - name: PROXY
          value: "true"
        ports:
         - containerPort: 8000
