resource "docker_container" "broker" {}
resource "docker_container" "vigorous_wilson" {}
resource "docker_container" "ksqldb-cli" {}
resource "docker_container" "control-center" {}
resource "docker_container" "ksql-datagen" {}
resource "docker_container" "ksqldb-server" {}
resource "docker_container" "connect" {}
resource "docker_container" "rest-proxy" {}
resource "docker_container" "schema-registry" {}
resource "docker_container" "zookeeper" {}
