apiVersion: v1
kind: Service
metadata:
  name: health-check-service
  namespace: health-check
spec:
  type: NodePort
  ports:
  - port: 3000
  selector:
    app: health-check-app
---
apiVersion: v1
kind: Pod
metadata:
  name: health-check
  namespace: health-check
  labels:
    app: health-check-app
spec:
  containers:
    - name: health-check
      image: <aws-account-id>.dkr.ecr.<aws-region>.amazonaws.com/<image-name>:<tag>
      imagePullPolicy: Always
      ports:
        - name: web
          containerPort: 3000
  imagePullSecrets:
      - name: regcred